### ISSUE TITLE
pw_iv column is not filled

### ISSUE THREAD

**Issue by powertim** [alpeinsoft-ch/teampass-api#1]
Hi,

I'm trying to use this API but I can't read passwords from db, output is like this:
 {
                "description": "",
                "email": "",
                "id": "249",
                "password": "",
                "title": "sql1-server-france",
                "type": "PASSWORD",
                "url": "",
                "username": "c2E="
   }

If I add a password with the API, I can successfully read it back, but anybody within Teampass will read the password.

The major difference in database is that the 'pw_iv' column is empty when adding password with API.

Could you fix it ?

Thanks.

**Comment by alpeinsoft-swiss** [comment]
Dear Mr X

The problem with API is known to us and we are working on it. 
We do not want to interfere in the Databasse of Team Pass therefore 
we are looking for a solution that we can integrate into API.

## 

Mit freundlichen Grüßen / Best regards,

EUGEN WILTOWSKI

CEO 
SAP Business Intelligence

ALPEIN Software SWISS AG

Flüelistrasse 13
Kerns 6064

Tel.:
Fax: 
Mobil:  +41 (0) 41 51 15 34-3
+41 (0) 41 51 15 34-9
+41 (0) 78 79 36 011
E-Mail: eugen.wiltowski mailto:eugen.wiltowski@alpeinsoft.de@alpeinsoft.ch mailto:philipp.kruse@alpeinsoft.ch
Web:    http://www.alpeinsoft.ch http://www.alpeinsoft.ch/

Geschäftsleitung: Eugen Wiltowski, Pavel Hasanov, Ulrich Schwendener Handelsregister: CHE-136.786.077

**Comment by alpeinsoft-swiss** [comment]
Dear Mr. Timothee,

As soon as we have this problem solved we will inform you immediatly.

## 

Mit freundlichen Grüßen / Best regards,

EUGEN WILTOWSKI

CEO 
SAP Business Intelligence

ALPEIN Software SWISS AG

Flüelistrasse 13
Kerns 6064

Tel.:
Fax: 
Mobil:  +41 (0) 41 51 15 34-3
+41 (0) 41 51 15 34-9
+41 (0) 78 79 36 011
E-Mail: eugen.wiltowski mailto:eugen.wiltowski@alpeinsoft.de@alpeinsoft.ch mailto:philipp.kruse@alpeinsoft.ch
Web:    http://www.alpeinsoft.ch http://www.alpeinsoft.ch/

Geschäftsleitung: Eugen Wiltowski, Pavel Hasanov, Ulrich Schwendener Handelsregister: CHE-136.786.077
