### ISSUE TITLE
Salt Key Issues

### ISSUE THREAD

**Issue by seancallaway** [alpeinsoft-ch/teampass-api#18]
Documentation shows

> please check salt in teampass, salt is defined in file sk.php

As of Teampass 2.1.27, the saltkey is stored in a different location and appears to be stored in an ASCII safe format from the Defuse library. I'm assuming (based on the 500 errors being generated) that teampass-api doesn't support this format?

Is there anything I can do to get this working with modern teampass?

**EDIT:** My 500 errors seemed to actually be linked to #14. However, I now just get an empty response.

**Comment by alpeinsoft-swiss** [comment]
Hi Sean,

unfortunately there’s no support beyond Version 2.1.23.
We developed our own password manager (https://www.pass-securium.ch) and are currently discussing the options how to handle the future of this api (community managed/closed down/new maintainer/etc.)
Until then no update will be released.

**Comment by seancallaway** [comment]
Alright. Thanks for the update.
